name: 'Deploy to AWS EC2 Sevice'

on:
  push:
    branches:
      - main

jobs:
  gitaction-ec2-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Repoitory Checkout code, 소스 가져오기 
          uses: actions/checkout@v4

        - name: Create SSH key file - pem 파일 생성
          run: |
            echo "${{ secrets.EC2_KEY }}" | base64 --decode > ./ec2_key.pem
            chmod 600 ./ec2_key.pem

        - name: EC2 환경 세팅 및 구동
          run: |
            ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              # 기존 프로세스 종료
              pkill -f gunicorn || true
              
              rm -rf grand-trade-auto
              git clone https://github.com/wjy4ng/grand-trade-auto.git
              cd grand-trade-auto
              
              uv sync
              
              # 프론트엔드 빌드
              cd front
              npm install
              npm run build
              
              # Django 설정
              cd ../server
              uv run manage.py migrate --noinput
              uv run manage.py collectstatic --noinput
            
              export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
              nohup uv run gunicorn --bind 0.0.0.0:8000 server.wsgi:application > gunicorn.log 2>&1 &
              
              sudo systemctl restart nginx
            EOF