name: 'Deploy to AWS EC2 Sevice'

on:
  push:
    branches:
      - main

jobs:
  gitaction-ec2-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Repoitory Checkout code, 소스 가져오기 
          uses: actions/checkout@v4

        - name: Create SSH key file - pem 파일 생성
          run: |
            echo "${{ secrets.EC2_KEY }}" | base64 --decode > ./ec2_key.pem
            chmod 600 ./ec2_key.pem

        - name: Deploy to EC2 instance - EC2 서버에 배포
          run: |
            scp -o StrictHostKeyChecking=no -i ./ec2_key.pem -r . ${{secrets.EC2_USER}}@${{ secrets.EC2_HOST }}:~

        - name: EC2 환경 세팅 및 구동
          run: |
            ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/grand-trade-auto
            uv run server/manage.py migrate --noinput
            uv run server/manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            EOF